#-------------------------------------------------------------------------------
# Unite
#-------------------------------------------------------------------------------
# Unite and create user interfaces
[[plugins]]
repo = 'Shougo/unite.vim'

# outline source for unite.vim
[[plugins]]
repo      = 'Shougo/unite-outline'
on_source = ['unite.vim']

# tags soruce for unite.vim
[[plugins]]
repo      = 'tsukkee/unite-tag'
on_source = ['unite.vim']

[[plugins]]
repo      = 'osyo-manga/unite-quickfix'
on_source = ['unite.vim']

[[plugins]] # A unite.vim plugin
repo      = 'ujihisa/unite-colorscheme' 
on_source = ['unite.vim']

[[plugins]] # Unite source for git conflicts.
repo      = 'moznion/unite-git-conflict.vim'
on_source = ['unite.vim']

[[plugins]] #  vim-unite-watson.vim is the unite source for watson.
repo      = 'alpaca-tc/vim-unite-watson.vim'
on_source = ['unite.vim']
on_cmd    = ['Watson']

[[plugins]]
repo      = 'Shougo/neomru.vim'
on_source = ['unite.vim']

#-------------------------------------------------------------------------------

# Powerful shell implemented by vim.
[[plugins]]
repo = 'Shougo/vimshell.vim'

# Next generation completion framework after neocomplcache
[[plugins]]
repo = 'Shougo/neocomplete.vim'
on_i = 1

# neo-snippet plugin contains neocomplcache snippets source
[[plugins]]
repo      = 'Shougo/neosnippet.vim'
on_source = ['neocomplete.vim']

# The standard snippets repository for neosnippet
[[plugins]]
repo      = 'Shougo/neosnippet-snippets'
on_source = ['neosnippet.vim']

# the world first vimshell plugin that you can run 'vim' command on ssh on vimshell
[[plugins]]
repo      = 'ujihisa/vimshell-ssh'
on_source = ['vimshell.vim']

[[plugins]]
repo   = 'thinca/vim-scouter'
on_cmd = ['Scouter']

[[plugins]] # Vim plugin for the_silver_searcher, 'ag', a replacement for the Perl module / CLI script 'ack'
repo   = 'rking/ag.vim'
on_cmd = ['Ag']
